### ISSUE TITLE
UTAPI auth V4 is incompatible with standard AWS-SDK

### ISSUE THREAD

**Issue by DavidPineauScality** [scality/utapi#91] opened 2017-01-25 16:06 UTC
Interacting with a customer attempting to use the UTAPI programmatically, I led an investigation done by @alexandre-merle.
We noticed that we could make a sample of code work with Arsenal's v2 auth, Arsenal's V4 auth, AWS-sdk V2 auth, but never AWS-SDK V4 auth.

We suspect that the way Arsenal sends Auth headers (and possibly receives and processes them) may be incompatible with the headers set by the AWS-SDK.

As an API that is expected to be usable by our customers,  I really think we should take a special care about compatibility with existing SDKs, so that access to the service can be easy, and not come back to us as support requests.

**Comment by rahulreddy** [comment] 2017-01-26 05:41
Here's the issue in Arsenal https://github.com/scality/Arsenal/pull/218

**Comment by bennettbuchanan** [comment] 2017-02-08 20:46
Duplicate of issue https://github.com/scality/utapi/issues/97.

Fixed with PR https://github.com/scality/utapi/pull/92.

**Closed** 2017-02-08 22:01 UTC
Labels: bug
